// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_contact_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_contact_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contact_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contact_2eproto;
namespace c_contact {
class Address;
struct AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Contacts;
struct ContactsDefaultTypeInternal;
extern ContactsDefaultTypeInternal _Contacts_default_instance_;
class PeopleInfo;
struct PeopleInfoDefaultTypeInternal;
extern PeopleInfoDefaultTypeInternal _PeopleInfo_default_instance_;
class PeopleInfo_RemarkEntry_DoNotUse;
struct PeopleInfo_RemarkEntry_DoNotUseDefaultTypeInternal;
extern PeopleInfo_RemarkEntry_DoNotUseDefaultTypeInternal _PeopleInfo_RemarkEntry_DoNotUse_default_instance_;
class PeopleInfo_phone;
struct PeopleInfo_phoneDefaultTypeInternal;
extern PeopleInfo_phoneDefaultTypeInternal _PeopleInfo_phone_default_instance_;
}  // namespace c_contact
PROTOBUF_NAMESPACE_OPEN
template<> ::c_contact::Address* Arena::CreateMaybeMessage<::c_contact::Address>(Arena*);
template<> ::c_contact::Contacts* Arena::CreateMaybeMessage<::c_contact::Contacts>(Arena*);
template<> ::c_contact::PeopleInfo* Arena::CreateMaybeMessage<::c_contact::PeopleInfo>(Arena*);
template<> ::c_contact::PeopleInfo_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage<::c_contact::PeopleInfo_RemarkEntry_DoNotUse>(Arena*);
template<> ::c_contact::PeopleInfo_phone* Arena::CreateMaybeMessage<::c_contact::PeopleInfo_phone>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace c_contact {

enum PeopleInfo_phone_Type : int {
  PeopleInfo_phone_Type_MP = 0,
  PeopleInfo_phone_Type_TEL = 1,
  PeopleInfo_phone_Type_PeopleInfo_phone_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PeopleInfo_phone_Type_PeopleInfo_phone_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PeopleInfo_phone_Type_IsValid(int value);
constexpr PeopleInfo_phone_Type PeopleInfo_phone_Type_Type_MIN = PeopleInfo_phone_Type_MP;
constexpr PeopleInfo_phone_Type PeopleInfo_phone_Type_Type_MAX = PeopleInfo_phone_Type_TEL;
constexpr int PeopleInfo_phone_Type_Type_ARRAYSIZE = PeopleInfo_phone_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PeopleInfo_phone_Type_descriptor();
template<typename T>
inline const std::string& PeopleInfo_phone_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PeopleInfo_phone_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PeopleInfo_phone_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PeopleInfo_phone_Type_descriptor(), enum_t_value);
}
inline bool PeopleInfo_phone_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PeopleInfo_phone_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PeopleInfo_phone_Type>(
    PeopleInfo_phone_Type_descriptor(), name, value);
}
// ===================================================================

class Address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:c_contact.Address) */ {
 public:
  inline Address() : Address(nullptr) {}
  ~Address() override;
  explicit PROTOBUF_CONSTEXPR Address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Address* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Address& from) {
    Address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "c_contact.Address";
  }
  protected:
  explicit Address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHomeAddressFieldNumber = 1,
    kUnitAddressFieldNumber = 2,
  };
  // string home_address = 1;
  void clear_home_address();
  const std::string& home_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_home_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_home_address();
  PROTOBUF_NODISCARD std::string* release_home_address();
  void set_allocated_home_address(std::string* home_address);
  private:
  const std::string& _internal_home_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_home_address(const std::string& value);
  std::string* _internal_mutable_home_address();
  public:

  // string unit_address = 2;
  void clear_unit_address();
  const std::string& unit_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_unit_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_unit_address();
  PROTOBUF_NODISCARD std::string* release_unit_address();
  void set_allocated_unit_address(std::string* unit_address);
  private:
  const std::string& _internal_unit_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_unit_address(const std::string& value);
  std::string* _internal_mutable_unit_address();
  public:

  // @@protoc_insertion_point(class_scope:c_contact.Address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr home_address_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr unit_address_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class PeopleInfo_phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:c_contact.PeopleInfo.phone) */ {
 public:
  inline PeopleInfo_phone() : PeopleInfo_phone(nullptr) {}
  ~PeopleInfo_phone() override;
  explicit PROTOBUF_CONSTEXPR PeopleInfo_phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeopleInfo_phone(const PeopleInfo_phone& from);
  PeopleInfo_phone(PeopleInfo_phone&& from) noexcept
    : PeopleInfo_phone() {
    *this = ::std::move(from);
  }

  inline PeopleInfo_phone& operator=(const PeopleInfo_phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeopleInfo_phone& operator=(PeopleInfo_phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeopleInfo_phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const PeopleInfo_phone* internal_default_instance() {
    return reinterpret_cast<const PeopleInfo_phone*>(
               &_PeopleInfo_phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PeopleInfo_phone& a, PeopleInfo_phone& b) {
    a.Swap(&b);
  }
  inline void Swap(PeopleInfo_phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeopleInfo_phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeopleInfo_phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeopleInfo_phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeopleInfo_phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeopleInfo_phone& from) {
    PeopleInfo_phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeopleInfo_phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "c_contact.PeopleInfo.phone";
  }
  protected:
  explicit PeopleInfo_phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PeopleInfo_phone_Type Type;
  static constexpr Type MP =
    PeopleInfo_phone_Type_MP;
  static constexpr Type TEL =
    PeopleInfo_phone_Type_TEL;
  static inline bool Type_IsValid(int value) {
    return PeopleInfo_phone_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    PeopleInfo_phone_Type_Type_MIN;
  static constexpr Type Type_MAX =
    PeopleInfo_phone_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    PeopleInfo_phone_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return PeopleInfo_phone_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return PeopleInfo_phone_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return PeopleInfo_phone_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_number();
  PROTOBUF_NODISCARD std::string* release_number();
  void set_allocated_number(std::string* number);
  private:
  const std::string& _internal_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .c_contact.PeopleInfo.phone.Type type = 2;
  void clear_type();
  ::c_contact::PeopleInfo_phone_Type type() const;
  void set_type(::c_contact::PeopleInfo_phone_Type value);
  private:
  ::c_contact::PeopleInfo_phone_Type _internal_type() const;
  void _internal_set_type(::c_contact::PeopleInfo_phone_Type value);
  public:

  // @@protoc_insertion_point(class_scope:c_contact.PeopleInfo.phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class PeopleInfo_RemarkEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PeopleInfo_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PeopleInfo_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  PeopleInfo_RemarkEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR PeopleInfo_RemarkEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit PeopleInfo_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PeopleInfo_RemarkEntry_DoNotUse& other);
  static const PeopleInfo_RemarkEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PeopleInfo_RemarkEntry_DoNotUse*>(&_PeopleInfo_RemarkEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "c_contact.PeopleInfo.RemarkEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "c_contact.PeopleInfo.RemarkEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_contact_2eproto;
};

// -------------------------------------------------------------------

class PeopleInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:c_contact.PeopleInfo) */ {
 public:
  inline PeopleInfo() : PeopleInfo(nullptr) {}
  ~PeopleInfo() override;
  explicit PROTOBUF_CONSTEXPR PeopleInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeopleInfo(const PeopleInfo& from);
  PeopleInfo(PeopleInfo&& from) noexcept
    : PeopleInfo() {
    *this = ::std::move(from);
  }

  inline PeopleInfo& operator=(const PeopleInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeopleInfo& operator=(PeopleInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeopleInfo& default_instance() {
    return *internal_default_instance();
  }
  enum OtherTypesCase {
    kQq = 4,
    kWechat = 5,
    OTHER_TYPES_NOT_SET = 0,
  };

  static inline const PeopleInfo* internal_default_instance() {
    return reinterpret_cast<const PeopleInfo*>(
               &_PeopleInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PeopleInfo& a, PeopleInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PeopleInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeopleInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeopleInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeopleInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeopleInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeopleInfo& from) {
    PeopleInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeopleInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "c_contact.PeopleInfo";
  }
  protected:
  explicit PeopleInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PeopleInfo_phone phone;

  // accessors -------------------------------------------------------

  enum : int {
    kPhoneNumbersFieldNumber = 2,
    kRemarkFieldNumber = 7,
    kNameFieldNumber = 1,
    kAnyFieldNumber = 3,
    kQqFieldNumber = 4,
    kWechatFieldNumber = 5,
  };
  // repeated .c_contact.PeopleInfo.phone phone_numbers = 2;
  int phone_numbers_size() const;
  private:
  int _internal_phone_numbers_size() const;
  public:
  void clear_phone_numbers();
  ::c_contact::PeopleInfo_phone* mutable_phone_numbers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo_phone >*
      mutable_phone_numbers();
  private:
  const ::c_contact::PeopleInfo_phone& _internal_phone_numbers(int index) const;
  ::c_contact::PeopleInfo_phone* _internal_add_phone_numbers();
  public:
  const ::c_contact::PeopleInfo_phone& phone_numbers(int index) const;
  ::c_contact::PeopleInfo_phone* add_phone_numbers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo_phone >&
      phone_numbers() const;

  // map<string, string> remark = 7;
  int remark_size() const;
  private:
  int _internal_remark_size() const;
  public:
  void clear_remark();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_remark();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_remark();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .google.protobuf.Any any = 3;
  bool has_any() const;
  private:
  bool _internal_has_any() const;
  public:
  void clear_any();
  const ::PROTOBUF_NAMESPACE_ID::Any& any() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_any();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_any();
  void set_allocated_any(::PROTOBUF_NAMESPACE_ID::Any* any);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_any() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_any();
  public:
  void unsafe_arena_set_allocated_any(
      ::PROTOBUF_NAMESPACE_ID::Any* any);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_any();

  // string qq = 4;
  bool has_qq() const;
  private:
  bool _internal_has_qq() const;
  public:
  void clear_qq();
  const std::string& qq() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qq(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qq();
  PROTOBUF_NODISCARD std::string* release_qq();
  void set_allocated_qq(std::string* qq);
  private:
  const std::string& _internal_qq() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qq(const std::string& value);
  std::string* _internal_mutable_qq();
  public:

  // string wechat = 5;
  bool has_wechat() const;
  private:
  bool _internal_has_wechat() const;
  public:
  void clear_wechat();
  const std::string& wechat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wechat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wechat();
  PROTOBUF_NODISCARD std::string* release_wechat();
  void set_allocated_wechat(std::string* wechat);
  private:
  const std::string& _internal_wechat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wechat(const std::string& value);
  std::string* _internal_mutable_wechat();
  public:

  void clear_other_types();
  OtherTypesCase other_types_case() const;
  // @@protoc_insertion_point(class_scope:c_contact.PeopleInfo)
 private:
  class _Internal;
  void set_has_qq();
  void set_has_wechat();

  inline bool has_other_types() const;
  inline void clear_has_other_types();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo_phone > phone_numbers_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        PeopleInfo_RemarkEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> remark_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::Any* any_;
    union OtherTypesUnion {
      constexpr OtherTypesUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qq_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wechat_;
    } other_types_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// -------------------------------------------------------------------

class Contacts final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:c_contact.Contacts) */ {
 public:
  inline Contacts() : Contacts(nullptr) {}
  ~Contacts() override;
  explicit PROTOBUF_CONSTEXPR Contacts(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Contacts(const Contacts& from);
  Contacts(Contacts&& from) noexcept
    : Contacts() {
    *this = ::std::move(from);
  }

  inline Contacts& operator=(const Contacts& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contacts& operator=(Contacts&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Contacts& default_instance() {
    return *internal_default_instance();
  }
  static inline const Contacts* internal_default_instance() {
    return reinterpret_cast<const Contacts*>(
               &_Contacts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Contacts& a, Contacts& b) {
    a.Swap(&b);
  }
  inline void Swap(Contacts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Contacts* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Contacts* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Contacts>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Contacts& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Contacts& from) {
    Contacts::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contacts* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "c_contact.Contacts";
  }
  protected:
  explicit Contacts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContactsFieldNumber = 1,
  };
  // repeated .c_contact.PeopleInfo contacts = 1;
  int contacts_size() const;
  private:
  int _internal_contacts_size() const;
  public:
  void clear_contacts();
  ::c_contact::PeopleInfo* mutable_contacts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo >*
      mutable_contacts();
  private:
  const ::c_contact::PeopleInfo& _internal_contacts(int index) const;
  ::c_contact::PeopleInfo* _internal_add_contacts();
  public:
  const ::c_contact::PeopleInfo& contacts(int index) const;
  ::c_contact::PeopleInfo* add_contacts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo >&
      contacts() const;

  // @@protoc_insertion_point(class_scope:c_contact.Contacts)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo > contacts_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contact_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Address

// string home_address = 1;
inline void Address::clear_home_address() {
  _impl_.home_address_.ClearToEmpty();
}
inline const std::string& Address::home_address() const {
  // @@protoc_insertion_point(field_get:c_contact.Address.home_address)
  return _internal_home_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_home_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.home_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.Address.home_address)
}
inline std::string* Address::mutable_home_address() {
  std::string* _s = _internal_mutable_home_address();
  // @@protoc_insertion_point(field_mutable:c_contact.Address.home_address)
  return _s;
}
inline const std::string& Address::_internal_home_address() const {
  return _impl_.home_address_.Get();
}
inline void Address::_internal_set_home_address(const std::string& value) {
  
  _impl_.home_address_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_home_address() {
  
  return _impl_.home_address_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_home_address() {
  // @@protoc_insertion_point(field_release:c_contact.Address.home_address)
  return _impl_.home_address_.Release();
}
inline void Address::set_allocated_home_address(std::string* home_address) {
  if (home_address != nullptr) {
    
  } else {
    
  }
  _impl_.home_address_.SetAllocated(home_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.home_address_.IsDefault()) {
    _impl_.home_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:c_contact.Address.home_address)
}

// string unit_address = 2;
inline void Address::clear_unit_address() {
  _impl_.unit_address_.ClearToEmpty();
}
inline const std::string& Address::unit_address() const {
  // @@protoc_insertion_point(field_get:c_contact.Address.unit_address)
  return _internal_unit_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_unit_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.unit_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.Address.unit_address)
}
inline std::string* Address::mutable_unit_address() {
  std::string* _s = _internal_mutable_unit_address();
  // @@protoc_insertion_point(field_mutable:c_contact.Address.unit_address)
  return _s;
}
inline const std::string& Address::_internal_unit_address() const {
  return _impl_.unit_address_.Get();
}
inline void Address::_internal_set_unit_address(const std::string& value) {
  
  _impl_.unit_address_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_unit_address() {
  
  return _impl_.unit_address_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_unit_address() {
  // @@protoc_insertion_point(field_release:c_contact.Address.unit_address)
  return _impl_.unit_address_.Release();
}
inline void Address::set_allocated_unit_address(std::string* unit_address) {
  if (unit_address != nullptr) {
    
  } else {
    
  }
  _impl_.unit_address_.SetAllocated(unit_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.unit_address_.IsDefault()) {
    _impl_.unit_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:c_contact.Address.unit_address)
}

// -------------------------------------------------------------------

// PeopleInfo_phone

// string number = 1;
inline void PeopleInfo_phone::clear_number() {
  _impl_.number_.ClearToEmpty();
}
inline const std::string& PeopleInfo_phone::number() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.phone.number)
  return _internal_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeopleInfo_phone::set_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.PeopleInfo.phone.number)
}
inline std::string* PeopleInfo_phone::mutable_number() {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.phone.number)
  return _s;
}
inline const std::string& PeopleInfo_phone::_internal_number() const {
  return _impl_.number_.Get();
}
inline void PeopleInfo_phone::_internal_set_number(const std::string& value) {
  
  _impl_.number_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo_phone::_internal_mutable_number() {
  
  return _impl_.number_.Mutable(GetArenaForAllocation());
}
inline std::string* PeopleInfo_phone::release_number() {
  // @@protoc_insertion_point(field_release:c_contact.PeopleInfo.phone.number)
  return _impl_.number_.Release();
}
inline void PeopleInfo_phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  _impl_.number_.SetAllocated(number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:c_contact.PeopleInfo.phone.number)
}

// .c_contact.PeopleInfo.phone.Type type = 2;
inline void PeopleInfo_phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::c_contact::PeopleInfo_phone_Type PeopleInfo_phone::_internal_type() const {
  return static_cast< ::c_contact::PeopleInfo_phone_Type >(_impl_.type_);
}
inline ::c_contact::PeopleInfo_phone_Type PeopleInfo_phone::type() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.phone.type)
  return _internal_type();
}
inline void PeopleInfo_phone::_internal_set_type(::c_contact::PeopleInfo_phone_Type value) {
  
  _impl_.type_ = value;
}
inline void PeopleInfo_phone::set_type(::c_contact::PeopleInfo_phone_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:c_contact.PeopleInfo.phone.type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PeopleInfo

// string name = 1;
inline void PeopleInfo::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PeopleInfo::name() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeopleInfo::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.PeopleInfo.name)
}
inline std::string* PeopleInfo::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.name)
  return _s;
}
inline const std::string& PeopleInfo::_internal_name() const {
  return _impl_.name_.Get();
}
inline void PeopleInfo::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_name() {
  // @@protoc_insertion_point(field_release:c_contact.PeopleInfo.name)
  return _impl_.name_.Release();
}
inline void PeopleInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:c_contact.PeopleInfo.name)
}

// repeated .c_contact.PeopleInfo.phone phone_numbers = 2;
inline int PeopleInfo::_internal_phone_numbers_size() const {
  return _impl_.phone_numbers_.size();
}
inline int PeopleInfo::phone_numbers_size() const {
  return _internal_phone_numbers_size();
}
inline void PeopleInfo::clear_phone_numbers() {
  _impl_.phone_numbers_.Clear();
}
inline ::c_contact::PeopleInfo_phone* PeopleInfo::mutable_phone_numbers(int index) {
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.phone_numbers)
  return _impl_.phone_numbers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo_phone >*
PeopleInfo::mutable_phone_numbers() {
  // @@protoc_insertion_point(field_mutable_list:c_contact.PeopleInfo.phone_numbers)
  return &_impl_.phone_numbers_;
}
inline const ::c_contact::PeopleInfo_phone& PeopleInfo::_internal_phone_numbers(int index) const {
  return _impl_.phone_numbers_.Get(index);
}
inline const ::c_contact::PeopleInfo_phone& PeopleInfo::phone_numbers(int index) const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.phone_numbers)
  return _internal_phone_numbers(index);
}
inline ::c_contact::PeopleInfo_phone* PeopleInfo::_internal_add_phone_numbers() {
  return _impl_.phone_numbers_.Add();
}
inline ::c_contact::PeopleInfo_phone* PeopleInfo::add_phone_numbers() {
  ::c_contact::PeopleInfo_phone* _add = _internal_add_phone_numbers();
  // @@protoc_insertion_point(field_add:c_contact.PeopleInfo.phone_numbers)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo_phone >&
PeopleInfo::phone_numbers() const {
  // @@protoc_insertion_point(field_list:c_contact.PeopleInfo.phone_numbers)
  return _impl_.phone_numbers_;
}

// .google.protobuf.Any any = 3;
inline bool PeopleInfo::_internal_has_any() const {
  return this != internal_default_instance() && _impl_.any_ != nullptr;
}
inline bool PeopleInfo::has_any() const {
  return _internal_has_any();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& PeopleInfo::_internal_any() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = _impl_.any_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& PeopleInfo::any() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.any)
  return _internal_any();
}
inline void PeopleInfo::unsafe_arena_set_allocated_any(
    ::PROTOBUF_NAMESPACE_ID::Any* any) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.any_);
  }
  _impl_.any_ = any;
  if (any) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:c_contact.PeopleInfo.any)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::release_any() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.any_;
  _impl_.any_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::unsafe_arena_release_any() {
  // @@protoc_insertion_point(field_release:c_contact.PeopleInfo.any)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.any_;
  _impl_.any_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::_internal_mutable_any() {
  
  if (_impl_.any_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    _impl_.any_ = p;
  }
  return _impl_.any_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* PeopleInfo::mutable_any() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_any();
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.any)
  return _msg;
}
inline void PeopleInfo::set_allocated_any(::PROTOBUF_NAMESPACE_ID::Any* any) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.any_);
  }
  if (any) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(any));
    if (message_arena != submessage_arena) {
      any = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, any, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.any_ = any;
  // @@protoc_insertion_point(field_set_allocated:c_contact.PeopleInfo.any)
}

// string qq = 4;
inline bool PeopleInfo::_internal_has_qq() const {
  return other_types_case() == kQq;
}
inline bool PeopleInfo::has_qq() const {
  return _internal_has_qq();
}
inline void PeopleInfo::set_has_qq() {
  _impl_._oneof_case_[0] = kQq;
}
inline void PeopleInfo::clear_qq() {
  if (_internal_has_qq()) {
    _impl_.other_types_.qq_.Destroy();
    clear_has_other_types();
  }
}
inline const std::string& PeopleInfo::qq() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.qq)
  return _internal_qq();
}
template <typename ArgT0, typename... ArgT>
inline void PeopleInfo::set_qq(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_qq()) {
    clear_other_types();
    set_has_qq();
    _impl_.other_types_.qq_.InitDefault();
  }
  _impl_.other_types_.qq_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.PeopleInfo.qq)
}
inline std::string* PeopleInfo::mutable_qq() {
  std::string* _s = _internal_mutable_qq();
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.qq)
  return _s;
}
inline const std::string& PeopleInfo::_internal_qq() const {
  if (_internal_has_qq()) {
    return _impl_.other_types_.qq_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PeopleInfo::_internal_set_qq(const std::string& value) {
  if (!_internal_has_qq()) {
    clear_other_types();
    set_has_qq();
    _impl_.other_types_.qq_.InitDefault();
  }
  _impl_.other_types_.qq_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_qq() {
  if (!_internal_has_qq()) {
    clear_other_types();
    set_has_qq();
    _impl_.other_types_.qq_.InitDefault();
  }
  return _impl_.other_types_.qq_.Mutable(      GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_qq() {
  // @@protoc_insertion_point(field_release:c_contact.PeopleInfo.qq)
  if (_internal_has_qq()) {
    clear_has_other_types();
    return _impl_.other_types_.qq_.Release();
  } else {
    return nullptr;
  }
}
inline void PeopleInfo::set_allocated_qq(std::string* qq) {
  if (has_other_types()) {
    clear_other_types();
  }
  if (qq != nullptr) {
    set_has_qq();
    _impl_.other_types_.qq_.InitAllocated(qq, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:c_contact.PeopleInfo.qq)
}

// string wechat = 5;
inline bool PeopleInfo::_internal_has_wechat() const {
  return other_types_case() == kWechat;
}
inline bool PeopleInfo::has_wechat() const {
  return _internal_has_wechat();
}
inline void PeopleInfo::set_has_wechat() {
  _impl_._oneof_case_[0] = kWechat;
}
inline void PeopleInfo::clear_wechat() {
  if (_internal_has_wechat()) {
    _impl_.other_types_.wechat_.Destroy();
    clear_has_other_types();
  }
}
inline const std::string& PeopleInfo::wechat() const {
  // @@protoc_insertion_point(field_get:c_contact.PeopleInfo.wechat)
  return _internal_wechat();
}
template <typename ArgT0, typename... ArgT>
inline void PeopleInfo::set_wechat(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_wechat()) {
    clear_other_types();
    set_has_wechat();
    _impl_.other_types_.wechat_.InitDefault();
  }
  _impl_.other_types_.wechat_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:c_contact.PeopleInfo.wechat)
}
inline std::string* PeopleInfo::mutable_wechat() {
  std::string* _s = _internal_mutable_wechat();
  // @@protoc_insertion_point(field_mutable:c_contact.PeopleInfo.wechat)
  return _s;
}
inline const std::string& PeopleInfo::_internal_wechat() const {
  if (_internal_has_wechat()) {
    return _impl_.other_types_.wechat_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PeopleInfo::_internal_set_wechat(const std::string& value) {
  if (!_internal_has_wechat()) {
    clear_other_types();
    set_has_wechat();
    _impl_.other_types_.wechat_.InitDefault();
  }
  _impl_.other_types_.wechat_.Set(value, GetArenaForAllocation());
}
inline std::string* PeopleInfo::_internal_mutable_wechat() {
  if (!_internal_has_wechat()) {
    clear_other_types();
    set_has_wechat();
    _impl_.other_types_.wechat_.InitDefault();
  }
  return _impl_.other_types_.wechat_.Mutable(      GetArenaForAllocation());
}
inline std::string* PeopleInfo::release_wechat() {
  // @@protoc_insertion_point(field_release:c_contact.PeopleInfo.wechat)
  if (_internal_has_wechat()) {
    clear_has_other_types();
    return _impl_.other_types_.wechat_.Release();
  } else {
    return nullptr;
  }
}
inline void PeopleInfo::set_allocated_wechat(std::string* wechat) {
  if (has_other_types()) {
    clear_other_types();
  }
  if (wechat != nullptr) {
    set_has_wechat();
    _impl_.other_types_.wechat_.InitAllocated(wechat, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:c_contact.PeopleInfo.wechat)
}

// map<string, string> remark = 7;
inline int PeopleInfo::_internal_remark_size() const {
  return _impl_.remark_.size();
}
inline int PeopleInfo::remark_size() const {
  return _internal_remark_size();
}
inline void PeopleInfo::clear_remark() {
  _impl_.remark_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PeopleInfo::_internal_remark() const {
  return _impl_.remark_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PeopleInfo::remark() const {
  // @@protoc_insertion_point(field_map:c_contact.PeopleInfo.remark)
  return _internal_remark();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PeopleInfo::_internal_mutable_remark() {
  return _impl_.remark_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PeopleInfo::mutable_remark() {
  // @@protoc_insertion_point(field_mutable_map:c_contact.PeopleInfo.remark)
  return _internal_mutable_remark();
}

inline bool PeopleInfo::has_other_types() const {
  return other_types_case() != OTHER_TYPES_NOT_SET;
}
inline void PeopleInfo::clear_has_other_types() {
  _impl_._oneof_case_[0] = OTHER_TYPES_NOT_SET;
}
inline PeopleInfo::OtherTypesCase PeopleInfo::other_types_case() const {
  return PeopleInfo::OtherTypesCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Contacts

// repeated .c_contact.PeopleInfo contacts = 1;
inline int Contacts::_internal_contacts_size() const {
  return _impl_.contacts_.size();
}
inline int Contacts::contacts_size() const {
  return _internal_contacts_size();
}
inline void Contacts::clear_contacts() {
  _impl_.contacts_.Clear();
}
inline ::c_contact::PeopleInfo* Contacts::mutable_contacts(int index) {
  // @@protoc_insertion_point(field_mutable:c_contact.Contacts.contacts)
  return _impl_.contacts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo >*
Contacts::mutable_contacts() {
  // @@protoc_insertion_point(field_mutable_list:c_contact.Contacts.contacts)
  return &_impl_.contacts_;
}
inline const ::c_contact::PeopleInfo& Contacts::_internal_contacts(int index) const {
  return _impl_.contacts_.Get(index);
}
inline const ::c_contact::PeopleInfo& Contacts::contacts(int index) const {
  // @@protoc_insertion_point(field_get:c_contact.Contacts.contacts)
  return _internal_contacts(index);
}
inline ::c_contact::PeopleInfo* Contacts::_internal_add_contacts() {
  return _impl_.contacts_.Add();
}
inline ::c_contact::PeopleInfo* Contacts::add_contacts() {
  ::c_contact::PeopleInfo* _add = _internal_add_contacts();
  // @@protoc_insertion_point(field_add:c_contact.Contacts.contacts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::c_contact::PeopleInfo >&
Contacts::contacts() const {
  // @@protoc_insertion_point(field_list:c_contact.Contacts.contacts)
  return _impl_.contacts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace c_contact

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::c_contact::PeopleInfo_phone_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::c_contact::PeopleInfo_phone_Type>() {
  return ::c_contact::PeopleInfo_phone_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_contact_2eproto
